services:
  # Build and run the DD4 MUD server
  server:
    platform: linux/amd64
    image: dd4-server
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./server/area:/dd4/external/area
      - ./server/player:/dd4/external/player
    # Uncomment to always restart:
    # restart: always
    stop_grace_period: 2s

  # Development environment
  # Use the native platform, otherwise gdb can have problems tracing on some archs
  dev:
    image: dd4-dev
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - "18888:8888"
    volumes:
      - ./server:/dd4-dev
      - ./builder:/dd4-dev/builder
    working_dir: /dd4-dev
    stop_grace_period: 2s
