version: '3'
services:

  # Build and run the DD4 MUD server
  server:
    image: dd4-server
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./server/area:/dd4/external/area
      - ./server/player:/dd4/external/player
    # Uncomment to always restart:
    # restart: always

  # Development environment
  dev:
    image: dd4-dev
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - "18888:8888"
    volumes:
      - ./server:/dd4-dev
    working_dir: /dd4-dev
