# docker-compose file for building and running the DD4 MUD server.

version: '3'
services:
  server:
    image: dd4-server
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./server/area:/dd4/external/area
      - ./server/player:/dd4/external/player
    restart: always
