import { useEffect } from 'react';
import './MapModal.css';

/*
  Intent: Display area map in a modal overlay with level warnings.
  
  This component shows a pre-generated HTML map for the current area in an iframe,
  with area metadata (title, level range) and optional level warnings when the
  player's level is below the minimum safe level for the area.
  
  Inputs:
    - mapData: Object containing { filename, name, levels } from maps.json
    - playerLevel: Current player level from Char.Vitals
    - onClose: Callback function to close the modal
  
  Outputs: Modal overlay with embedded map iframe
  
  Preconditions: mapData must be valid, iframe source must be accessible
  Postconditions: Modal displays map, ESC key closes modal
  
  Failure Behavior: If map fails to load, iframe will show browser error
  
  Performance: Iframe load is async, may take 100-500ms for large maps
  
  Notes: Maps are static HTML files generated by MapMaker v0.3
*/
function MapModal({ mapData, playerLevel, onClose }) {
  useEffect(() => {
    const handleEscape = (e) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };
    
    document.addEventListener('keydown', handleEscape);
    return () => document.removeEventListener('keydown', handleEscape);
  }, [onClose]);

  if (!mapData) return null;

  // Parse level range to determine if player is below minimum
  const showWarning = () => {
    if (!mapData.levels || mapData.levels.includes('All levels') || mapData.levels.includes('Unknown')) {
      return false;
    }

    // Parse "Levels 5-10" or "Level 100" format
    const levelMatch = mapData.levels.match(/Levels?\s+(\d+)/);
    if (levelMatch) {
      const minLevel = parseInt(levelMatch[1], 10);
      return playerLevel < minLevel;
    }

    return false;
  };

  const isUnderleveled = showWarning();

  return (
    <div className="map-modal-overlay" onClick={onClose}>
      <div className="map-modal-content" onClick={(e) => e.stopPropagation()}>
        <div className="map-modal-header">
          <div className="map-modal-title">
            <h2>{mapData.name}</h2>
            <span className="map-modal-levels">{mapData.levels}</span>
          </div>
          <button className="map-modal-close" onClick={onClose} aria-label="Close map">
            ×
          </button>
        </div>
        
        {isUnderleveled && (
          <div className="map-modal-warning">
            ⚠️ Warning: You are below the recommended level for this area!
          </div>
        )}
        
        <div className="map-modal-body">
          <iframe
            src={`/maps/area/${mapData.filename}`}
            title={`Map of ${mapData.name}`}
            className="map-modal-iframe"
          />
        </div>
      </div>
    </div>
  );
}

export default MapModal;
